import csv
from pathlib import Path

import psycopg
from dotenv import dotenv_values
from psycopg import sql


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_ROOT = PROJECT_ROOT / "data" / "ptb-xl-1.0.3"

ECG_CSV = DATA_ROOT / "ptbxl_database.csv"
SCP_CSV = DATA_ROOT / "scp_statements.csv"
ENV_FILE = PROJECT_ROOT / ".env"

ECG_COLUMNS = [
    "ecg_id",
    "patient_id",
    "age",
    "sex",
    "height",
    "weight",
    "nurse",
    "site",
    "device",
    "recording_date",
    "report",
    "scp_codes",
    "heart_axis",
    "infarction_stadium1",
    "infarction_stadium2",
    "validated_by",
    "second_opinion",
    "initial_autogenerated_report",
    "validated_by_human",
    "baseline_drift",
    "static_noise",
    "burst_noise",
    "electrodes_problems",
    "extra_beats",
    "pacemaker",
    "strat_fold",
    "filename_lr",
    "filename_hr",
]

SCP_SOURCE_TO_TARGET = [
    ("description", "description"),
    ("diagnostic", "diagnostic"),
    ("form", "form"),
    ("rhythm", "rhythm"),
    ("diagnostic_class", "diagnostic_class"),
    ("diagnostic_subclass", "diagnostic_subclass"),
    ("Statement Category", "statement_category"),
    ("SCP-ECG Statement Description", "scp_ecg_statement_description"),
    ("AHA code", "aha_code"),
    ("aECG REFID", "aecg_refid"),
    ("CDISC Code", "cdisc_code"),
    ("DICOM Code", "dicom_code"),
]


def copy_csv(cursor, csv_path, schema, table, source_to_target):
    target_columns = [target for _, target in source_to_target]

    copy_query = sql.SQL("COPY {}.{} ({}) FROM STDIN").format(
        sql.Identifier(schema),
        sql.Identifier(table),
        sql.SQL(", ").join(sql.Identifier(name) for name in target_columns),
    )

    row_count = 0

    with csv_path.open("r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)
        source_columns = reader.fieldnames or []

        missing_columns = [
            source
            for source, _ in source_to_target
            if source not in source_columns
        ]
        if missing_columns:
            raise ValueError(
                f"{csv_path.name} thiếu các cột: {missing_columns}"
            )

        with cursor.copy(copy_query) as copy:
            for row in reader:
                values = tuple(
                    row.get(source) or None
                    for source, _ in source_to_target
                )
                copy.write_row(values)
                row_count += 1

    return row_count


def copy_scp_csv(cursor, csv_path):
    target_columns = [
        "scp_code",
        *[target for _, target in SCP_SOURCE_TO_TARGET],
    ]

    copy_query = sql.SQL("COPY raw.ptbxl_scp_statement_source ({}) FROM STDIN").format(
        sql.SQL(", ").join(sql.Identifier(name) for name in target_columns)
    )

    row_count = 0

    with csv_path.open("r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)
        source_columns = reader.fieldnames or []

        if not source_columns:
            raise ValueError(f"{csv_path.name} không có header")

        # Cột đầu tiên của file CSV chứa mã SCP, dù tên header để trống.
        code_column = source_columns[0]

        missing_columns = [
            source
            for source, _ in SCP_SOURCE_TO_TARGET
            if source not in source_columns
        ]
        if missing_columns:
            raise ValueError(
                f"{csv_path.name} thiếu các cột: {missing_columns}"
            )

        with cursor.copy(copy_query) as copy:
            for row in reader:
                values = [row.get(code_column) or None]

                for source, target in SCP_SOURCE_TO_TARGET:
                    value = row.get(source) or None

                    if target in {"diagnostic", "form", "rhythm"} and value is not None:
                        value = str(int(float(value)))

                    values.append(value)

                copy.write_row(tuple(values))
                row_count += 1

    return row_count


def main():
    if not ENV_FILE.is_file():
        raise FileNotFoundError(
            "Không tìm thấy .env ở thư mục gốc dự án."
        )

    settings = dotenv_values(ENV_FILE)
    required = ["POSTGRES_DB", "POSTGRES_USER", "POSTGRES_PASSWORD"]
    missing_settings = [
        name for name in required if not settings.get(name)
    ]

    if missing_settings:
        raise ValueError(
            f".env thiếu giá trị cho: {missing_settings}"
        )

    connection_settings = {
        "host": settings.get("POSTGRES_HOST") or "localhost",
        "port": int(settings.get("POSTGRES_PORT") or "5432"),
        "dbname": settings["POSTGRES_DB"],
        "user": settings["POSTGRES_USER"],
        "password": settings["POSTGRES_PASSWORD"],
    }

    with psycopg.connect(**connection_settings) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                TRUNCATE TABLE
                    raw.ptbxl_ecg_source,
                    raw.ptbxl_scp_statement_source
                """
            )

            ecg_count = copy_csv(
                cursor=cursor,
                csv_path=ECG_CSV,
                schema="raw",
                table="ptbxl_ecg_source",
                source_to_target=[(name, name) for name in ECG_COLUMNS],
            )

            scp_count = copy_scp_csv(cursor, SCP_CSV)

    print(f"Đã nạp ECG metadata: {ecg_count:,} dòng")
    print(f"Đã nạp từ điển SCP: {scp_count:,} dòng")
    print("Transaction đã commit thành công.")


if __name__ == "__main__":
    main()