CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS mart;

CREATE TABLE IF NOT EXISTS raw.ptbxl_ecg_source (
    ecg_id INTEGER PRIMARY KEY,
    patient_id NUMERIC,
    age NUMERIC,
    sex SMALLINT,
    height NUMERIC,
    weight NUMERIC,
    nurse NUMERIC,
    site NUMERIC,
    device TEXT,
    recording_date TIMESTAMP WITHOUT TIME ZONE,
    report TEXT,
    scp_codes TEXT,
    heart_axis TEXT,
    infarction_stadium1 TEXT,
    infarction_stadium2 TEXT,
    validated_by TEXT,
    second_opinion BOOLEAN,
    initial_autogenerated_report BOOLEAN,
    validated_by_human BOOLEAN,
    baseline_drift TEXT,
    static_noise TEXT,
    burst_noise TEXT,
    electrodes_problems TEXT,
    extra_beats TEXT,
    pacemaker TEXT,
    strat_fold SMALLINT,
    filename_lr TEXT,
    filename_hr TEXT,
    source_file TEXT NOT NULL DEFAULT 'ptbxl_database.csv',
    dataset_version TEXT NOT NULL DEFAULT '1.0.3',
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw.ptbxl_scp_statement_source (
    scp_code TEXT PRIMARY KEY,
    description TEXT,
    diagnostic SMALLINT,
    form SMALLINT,
    rhythm SMALLINT,
    diagnostic_class TEXT,
    diagnostic_subclass TEXT,
    statement_category TEXT,
    scp_ecg_statement_description TEXT,
    aha_code TEXT,
    aecg_refid TEXT,
    cdisc_code TEXT,
    dicom_code TEXT,
    source_file TEXT NOT NULL DEFAULT 'scp_statements.csv',
    dataset_version TEXT NOT NULL DEFAULT '1.0.3',
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);